### ISSUE TITLE
Trigger lazyloading of elements from outside of Angular. (Question)

### ISSUE THREAD

**Issue by michaelkrog** [juristr/ngx-lazy-el#9]
Is it possible to somehow to trigger the lazyload from outside the Angular application?

We have a huge old UI we want to progressively change to Angular. We would like to use build WebComponents in Angular, and wonder if we can use ngx-lazy-el to register all our modules in one application, and then have them lazy load when they are used  on the page loading the Angular application.

I did do a test and see that I can use the lazyloaded customElement outside of the Angular application - but only after it has been lazy-loaded.

**Comment by ilchenkob** [comment]
@michaelkrog 
I have similar case on our project. And so far I found [this](https://github.com/brunob15/ngx-element). It works well, allows to lazy load elements from outside of Angular app, but there are some issues with dependency injection (from what I discovered lazy loaded module will have it's own instance of dependency tree).

**Comment by juristr** [comment]
It is definitely possible. This library specifically was made for the use case of dynamically loading Angular components within an existing Angular app, so the triggering of the lazy loading was developed in the most seamless way possible.

In your scenario, that triggering of the loading of the lazy bundle would need to be explicit, s.t. you can invoke a function, give it a JS file which gets downloaded and bootstrapped, and which then contains the logic of the Angular element.
